version: "3.8"

services:
  frontend:
    image: wajeeha835/brewandblissfrontend:v0
    container_name: frontend-container
    environment:
      - REACT_APP_CUSTOMER_SERVICE_URL=http://35.244.41.8:8000/register
      - REACT_APP_ORDER_SERVICE_URL=http://35.244.41.8:8080/order
    networks:
      - custom-network
    ports:
      - "3000:3000"
    depends_on:
      - customer-service
      - order-service
      - notification-service

  customer-service:
    image: wajeeha835/customerservice:v0
    container_name: customer
    environment:
      - MONGODB_URI=mongodb://db:27017
      - DB_NAME=coffeshop
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - custom-network
    ports:
      - "8000:8000"
    depends_on:
      - db

  order-service:
    image: wajeeha835/orderservice:v0
    container_name: order
    environment:
      - MONGO_URI=mongodb://db:27017
      - DB_NAME=coffee_tracker
      - CUSTOMER_SERVICE_URL=http://customer-service:8000
      - QUEUE_SERVICE_URL=http://notification-service:9000
      - ORDER_SERVICE_PORT=8080
    networks:
      - custom-network
    ports:
      - "8080:8080"
    depends_on:
      - db

  notification-service:
    image: wajeeha835/notificationservice:v0
    container_name: notification
    environment:
      - EMAIL=f219119@cfd.nu.edu.pk
      - EMAIL_PASSWORD=vjnh iwpx bokx timh
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - PORT=9000
    networks:
      - custom-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    networks:
      - custom-network
    volumes:
      - db-data:/data/db

networks:
  custom-network:
    driver: bridge

volumes:
  db-data:

