apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: wajeeha835/customerservice:v2
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        - name: DB_NAME
          value: "coffeshop"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: customer-service
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
