apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: wajeeha835/orderservice:v4
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
        - name: DB_NAME
          value: "coffee_tracker"
        - name: CUSTOMER_SERVICE_URL
          value: "http://customer-service:8000"
        - name: QUEUE_SERVICE_URL
          value: "http://notification-service:9000"
        - name: ORDER_SERVICE_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: order-service
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
