{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  labels:
    {{- range $key, $value := .Values.persistentVolumeClaim.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.spec.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.spec.resources.requests.storage }}
  storageClassName: {{ .Values.persistentVolumeClaim.spec.storageClassName }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.persistentVolumeClaim.spec.selector.matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
{{- end }}
